CREATE TABLE 
STUDENT_DETAILS (
STUDENT_ID INT AUTO_INCREMENT ,
NAME VARCHAR(20),
ROLL_NUMBER VARCHAR(10),
CLASS INT,
SECTION VARCHAR(2),
ADDRESS_LINE VARCHAR(50),
CITY VARCHAR(20),
STATE VARCHAR(20),
PIN_CODE VARCHAR(20),
MOBILE_NUMBER VARCHAR(10),
EMAIL_ID VARCHAR(50),
CREATED_DATE DATETIME,
PRIMARY KEY (STUDENT_ID)
)